97 add pin/unpin functionality to pinned view
TUM-Dev/gocast_mobile pull request #127
Opened 2023-12-15 10:51 UTC by cbetul

## Changes
- Implement functionality for a pinned courses view, allowing users to pin and unpin courses.
- Users should be able to view all currently pinned courses.

## Resolves
closes #97

2023-12-15 10:55 UTC, cbetul commented
## TODO:            
   @carlobortolan : 
    
The empty pinned courses view looks correct now, but doesn't reload when pulling/scrolling down:

This is how it should look like when refreshing the view:
![Screenshot_20231214_043714-1](https://github.com/TUM-Dev/gocast_mobile/assets/106114526/14da651c-9d0e-46cf-be52-fc8934b3f2a2)

_Originally posted by @carlobortolan in https://github.com/TUM-Dev/gocast_mobile/pull/125#pullrequestreview-1780895536_

2023-12-16 13:57 UTC, GravityDarkLab approved these changes, later dismissed

2023-12-16 13:57 UTC, GravityDarkLab commented on lib/views/course_view/components/pinned_course_view.dart
> +import '../../../base/networking/api/gocast/api_v2.pb.dart';
change this import to `package:......`

2023-12-16 13:58 UTC, GravityDarkLab commented
> ## TODO:
> @carlobortolan :
> 
> The empty pinned courses view looks correct now, but doesn't reload when pulling/scrolling down:
> 
> This is how it should look like when refreshing the view: ![Screenshot_20231214_043714-1](https://private-user-images.githubusercontent.com/106114526/290392278-14da651c-9d0e-46cf-be52-fc8934b3f2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzUzNDksIm5iZiI6MTcwMjczNTA0OSwicGF0aCI6Ii8xMDYxMTQ1MjYvMjkwMzkyMjc4LTE0ZGE2NTFjLTlkMGUtNDZjZi1iZTUyLWZjODkzNGIzZjJhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMzU3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjFmNzhlZDZkZTYzNmM3Yjc0YTBlZGZkYWViYmZjMmJhMmU2ODk0ZTU4NDZmMDJiY2JkNmYxNTBkNjYxYjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gv--WyaWitUNYMsybqoQO2ESWk2x4C7i1fd6ei16gLM)
> 
> _Originally posted by @carlobortolan in [#125 (review)](https://github.com/TUM-Dev/gocast_mobile/pull/125#pullrequestreview-1780895536)_

Also either fix this or create an issue for it

2023-12-16 14:28 UTC, carlobortolan requested changes
The code looks good to me for the most part :+1: 
Just two remarks before I would approve the PR: 
1. The reloading issue when no courses are pinned (https://github.com/TUM-Dev/gocast_mobile/pull/127#issuecomment-1857682139) still isn't solved
2. Is there a specific reason why you put both the components for the pinned courses in the same directory as the components for the downloads (`./lib/views/course_view/downloaded_pinned_courses_view`) ? If not, maybe copy the components for the pinned courses in a dedicated folder (e.g. `./lib/views/course_view/pinned_view` and the download related views to `./lib/views/course_view/download_view`) so that we keep an organized code structure

2023-12-16 14:28 UTC, carlobortolan commented on lib/views/course_view/components/pinned_course_view.dart
Please rename file to `pinned_course_card.dart` to keep naming of the files consistent with the classes/components defined in those files.

2023-12-16 14:28 UTC, carlobortolan commented on lib/views/course_view/components/pinned_courses_list.dart
See comment above regarding naming of files. 
To avoid confusion, the file should have the same name as the class it defines, so in this case either rename the file to `pinned_course_list.dart` or change the class name to `PinnedCoursesList`

2023-12-17 12:50 UTC, cbetul commented on lib/views/course_view/components/pinned_courses_list.dart
Fixed

2023-12-17 12:53 UTC, cbetul commented
@carlobortolan @GravityDarkLab 

1. I will open a separate issue for the reloading issue. This merge request includes functionality only. I'm trying to make the task more modular, as we talked about in the last meeting.
2. At first, the pinned view and course view used the same components and were under the same directory. I used the same structure because I didn't want to change the file structure too much. However, I created a separate folder that can be seen in my last commit.

2023-12-17 12:56 UTC, cbetul commented on lib/views/course_view/components/pinned_course_view.dart
> +import '../../../base/networking/api/gocast/api_v2.pb.dart';
done

2023-12-17 13:44 UTC, GravityDarkLab approved these changes
Seems fine to me, as an issue was now created.

2023-12-17 14:07 UTC, carlobortolan approved these changes

2023-12-17 14:07 UTC, merged