136 implement course view
TUM-Dev/gocast_mobile pull request #164
Opened 2023-12-27 19:34 UTC by Sainaamr

**What was done:**

- create a UI for the detail course
- fetching the streams for a course and updating the view accordingly 
- fetching the thumbnails live or not 
- showing the thumbnails

**things that most likely going to change:** 

- how the thumbnails look (waiting to see the course over view thumbnails and then change accordingly)

2023-12-27 20:24 UTC, cbetul commented
I think it looks pretty good, I haven't come across any functional flaws or bugs. I just have a few suggestions:
- The navigation bar should look like in the Figma (search input is not hidden, back arrow icon etc.), for example, it should look like this:
<img width="230" alt="Screenshot 2023-12-27 at 21 13 10" src="https://github.com/TUM-Dev/gocast_mobile/assets/43902289/85b2e1e1-d6d8-4e3e-899d-e3f179ca90a1">

- You can adjust the padding of the course cards, it looked like slightly overloaded horizontally to me.

2023-12-27 20:25 UTC, cbetul commented on lib/models/user/user_state_model.dart
> +  //final List<Stream>? courseStreams; // New property for course streams
don't forget to remove comments :)

2023-12-27 20:26 UTC, cbetul commented on lib/views/course_detail_view/stream_card.dart
> +              padding: EdgeInsets.fromLTRB(8.0, 8.0, 8.0, 12.0),
You can adjust the padding of the course cards, it looked like slightly overloaded horizontally to me.

2023-12-27 20:27 UTC, cbetul commented on lib/views/course_detail_view/detail_course_List.dart
> +          icon: const Icon(Icons.search),
I think it looks pretty good, I haven't come across any functional flaws or bugs. I just have a few suggestions:
- The navigation bar should look like in the Figma (search input is not hidden, back arrow icon etc.), for example, it should look like this:
<img width="230" alt="Screenshot 2023-12-27 at 21 13 10" src="https://github.com/TUM-Dev/gocast_mobile/assets/43902289/85b2e1e1-d6d8-4e3e-899d-e3f179ca90a1">

2023-12-27 20:28 UTC, cbetul requested changes
I think it looks pretty good, I haven't come across any functional flaws or bugs. I just have a few suggestions:

2023-12-27 20:42 UTC, Anishyou requested changes
There is a bug where I cannot go back when I click on a course. THere is no back button, no nav bar nothing?






https://github.com/TUM-Dev/gocast_mobile/assets/123313052/14e32cea-8f1c-4ec2-8598-64b433eceee4

2023-12-28 11:11 UTC, Sainaamr commented
> There is a bug where I cannot go back when I click on a course. THere is no back button, no nav bar nothing?
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.Max.-.2023-12-27.at.21.41.54.mp4


https://github.com/TUM-Dev/gocast_mobile/assets/90347142/d5de32dd-6c64-48da-bbc9-070e7605216c

I dont have the bug. i ran it on iphone 15 pro max too.

2023-12-28 11:14 UTC, Anishyou commented
> > There is a bug where I cannot go back when I click on a course. THere is no back button, no nav bar nothing?
> > Simulator.Screen.Recording.-.iPhone.15.Pro.Max.-.2023-12-27.at.21.41.54.mp4
> 
>  Screen.Recording.2023-12-28.at.12.08.46.mov 
> I dont have the bug. i ran it on iphone 15 pro max too. do you know where is the problem?

Firstly I think you should update your branch with dev. I have solved the navigation issues.

2023-12-28 12:05 UTC, Anishyou commented
> > There is a bug where I cannot go back when I click on a course. THere is no back button, no nav bar nothing?
> > Simulator.Screen.Recording.-.iPhone.15.Pro.Max.-.2023-12-27.at.21.41.54.mp4
> 
>  Screen.Recording.2023-12-28.at.12.08.46.mov 
> I dont have the bug. i ran it on iphone 15 pro max too. do you know where is the problem?

I checked again. As I sent the video, error is still there. which branch are you working on?
136-implement-course-view right?

2023-12-28 12:38 UTC, Anishyou commented
<img width="327" alt="Screenshot 2023-12-28 at 13 38 02" src="https://github.com/TUM-Dev/gocast_mobile/assets/123313052/9f47ecd0-0283-480d-9857-7644d963a391">

I would suggest to add some mock data for course video so that we see how it looks. It is not needed now , you can create another PR for it also.

2023-12-28 14:03 UTC, Sainaamr commented
> <img alt="Screenshot 2023-12-28 at 13 38 02" width="327" src="https://private-user-images.githubusercontent.com/123313052/293206585-9f47ecd0-0283-480d-9857-7644d963a391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzI0MzMsIm5iZiI6MTcwMzc3MjEzMywicGF0aCI6Ii8xMjMzMTMwNTIvMjkzMjA2NTg1LTlmNDdlY2QwLTAyODMtNDgwZC05ODU3LTc2NDRkOTYzYTM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxNDAyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2M1YWM4Mjk1MjNiOWM5MzZjNDhhMDljMDVlYjIwYTBlZTVmYjk5NmM3N2RhYTljNWViZjZiNWM5MTBmMzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z4pcO_yIEiIkbic_RWhVvpFTA_JdoT7L7ex6OWiLGJY">
> I would suggest to add some mock data for course video so that we see how it looks. It is not needed now , you can create another PR for it also.

i have a question why dont u have any streams showing but i do?

2023-12-28 14:04 UTC, Sainaamr commented
now the bug is not there?

2023-12-28 14:10 UTC, Anishyou commented
> now the bug is not there?

yes it is solved

2023-12-28 15:50 UTC, GravityDarkLab requested changes

2023-12-28 15:50 UTC, GravityDarkLab commented on lib/view_models/stream_view_model.dart
> +          await StreamHandler(_grpcHandler).fetchThumbnailVOD(streamId);
should be like this?

```suggestion
          await StreamHandler(_grpcHandler).fetchThumbnailStreams(streamId);
```

2023-12-28 15:50 UTC, GravityDarkLab commented on lib/view_models/stream_view_model.dart
Looks good.
An Idea how you can refactor the thumbnails fetching:

```Dart
Future<void> fetchThumbnails() async {
    if (state.streams == null) {
      return;
    }
    var fetchThumbnailTasks = state.streams!
        .map((stream) => fetchThumbnailForStream(stream))
        .toList();

    var fetchedThumbnails = await Future.wait(fetchThumbnailTasks);
    state = state.copyWith(thumbnails: fetchedThumbnails, isLoading: false);
  }

  Future<String> fetchThumbnailForStream(Stream stream) async {
    try {
      return await (stream.liveNow
          ? fetchStreamThumbnail(stream.id)
          : fetchVODThumbnail(stream.id));
    } catch (e) {
      _logger.e('Error fetching thumbnail for stream ID ${stream.id}: $e');
      return '/thumb-fallback.png'; // Fallback thumbnail
    }
  }

  Future<String> fetchStreamThumbnail(Int64 streamId) async {
    try {
      _logger.i('Fetching thumbnail for live stream ID: $streamId');
      return await StreamHandler(_grpcHandler).fetchThumbnailStreams(streamId);
    } catch (e) {
      _logger.e('Error fetching thumbnail for live stream: $e');
      rethrow;
    }
  }

  Future<String> fetchVODThumbnail(Int64 streamId) async {
    try {
      _logger.i('Fetching thumbnail for VOD stream ID: $streamId');
      return await StreamHandler(_grpcHandler).fetchThumbnailVOD(streamId);
    } catch (e) {
      _logger.e('Error fetching thumbnail for VOD stream: $e');
      rethrow;
    }
  }
```

2023-12-28 15:50 UTC, GravityDarkLab commented on lib/views/course_view/components/course_card_view.dart
> +import '../../course_detail_view/course_detail_view.dart';
```suggestion
import 'package:gocast_mobile/views/course_detail_view/course_detail_view.dart';
```

2023-12-28 15:50 UTC, GravityDarkLab commented on lib/views/course_detail_view/course_detail_view.dart
> +import '../components/custom_search_top_nav_bar_back:button.dart';
```suggestion
import 'package:gocast_mobile/views/components/custom_search_top_nav_bar_back:button.dart';
```

2023-12-28 19:38 UTC, GravityDarkLab approved these changes
Looks good to me

2023-12-28 19:52 UTC, Anishyou approved these changes

2023-12-28 20:53 UTC, cbetul approved these changes
looks fine

2023-12-28 21:40 UTC, merged